version: '3.8'

services:
  app:
    build: .
    container_name: ${APP_CONTAINER:-wordpress_dev}
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: ${DB_CONTAINER:-wordpress_db}:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  browsersync:
    image: node:18-alpine 
    container_name: ${BS_CONTAINER:-browsersync}
    working_dir: /app
    volumes:
      - ./browsersync:/app
      - ./wordpress:/app/wordpress
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "npm install && npx browser-sync start --config bs-config.js"
    depends_on:
      - app

  db:
    image: mysql:9
    container_name: ${DB_CONTAINER:-wordpress_db}
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PMA_CONTAINER:-phpmyadmin}
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
